### ISSUE TITLE
Cannot connect to wifi lan

### ISSUE THREAD

**Issue by jdhysell** [MilovdZee/LEDCircleClock#2]
I run several wifi lan segments. A couple are open with no password, and others are password protected. I can connect to the ESP8266 while it is in access point mode, and configure the wifi setup to point to the wifi lans, but upon reboot, the ESP8266 attempts to connect and fails - all segments fail - with or with no password protection.  (Attempts are visible in the serial output session) Am I missing something here? Thanks for any help. Really looking forward to getting this clock running. 3D prints are done - just waiting for the programming...

**Comment by MilovdZee** [comment]
Are any of the access points you tried in the 2.4GHz band? I also noticed that some access points have WPA3 and I think the ESP only supports WPA. Not even WPA2. But I'm not sure.

I checked the setup by enabling the hotspot on my phone and that worked.

**Comment by jdhysell** [comment]
Yes. All access points support 2.4 GHz.I don't have WPA engaged. I can set one AP to use WPA and test that.
thanks for the suggestion.-John
    On Tuesday, April 20, 2021, 02:49:49 PM EDT, MilovdZee ***@***.***> wrote:  
 
 


Are any of the access points you tried in the 2.4GHz band? I also noticed that some access points have WPA3 and I think the ESP only supports WPA. Not even WPA2. But I'm not sure.

I checked the setup by enabling the hotspot on my phone and that worked.

**Comment by MilovdZee** [comment]
And open access point probably don't work with the current code. The sketch just always sends the username and password. Please let me know if you get it to work. Else I can try to allow for open access points.

**Comment by MilovdZee** [comment]
And nice that you are building one. I'm enjoying mine very much :)

**Comment by jdhysell** [comment]
I live in a very rural area in central New York. (Nearest neighbor is 1/4 mile away...)
So AP security is not high on my priority listRunning open AP's makes connectivity fast and simple
8-)

    On Tuesday, April 20, 2021, 03:00:46 PM EDT, MilovdZee ***@***.***> wrote:  
 
 


And open access point probably don't work with the current code. The sketch just always sends the username and password. Please let me know if you get it to work. Else I can try to allow for open access points.

**Comment by jdhysell** [comment]
hmmmno joy using an AP running WPA
see serial output below:-----------------------------------------------------onnecting to WIFI 'store'...Connection Failed! Continuing...IP address: (IP unset)
Running...
----------------------------------------------------
AP settings:



    On Tuesday, April 20, 2021, 03:00:46 PM EDT, MilovdZee ***@***.***> wrote:  
 
 


And open access point probably don't work with the current code. The sketch just always sends the username and password. Please let me know if you get it to work. Else I can try to allow for open access points.

**Comment by MilovdZee** [comment]
Weird. And when you use your phone as access point? 
And maybe try with a different ESP? Although this would be unexpected because you say that connecting to it when it is in access point mode is fine.

**Comment by MilovdZee** [comment]
You could also try your open networks by changing one line of code:
replace:
`WiFi.begin(String(ssid), String(wifiPassword));`
with
`WiFi.begin(String(ssid));`

**Comment by jdhysell** [comment]
not an option - my cell phone plan has no data included.(OK - I am cheap...)
I will modify the WIFI code as you suggest and try again.
I may also try moving closer to the AP.It could be a range limitation on the ESP8266.When I connect to it, my laptop is right next to it.
thx again for your support.-John
    On Wednesday, April 21, 2021, 02:51:30 AM EDT, MilovdZee ***@***.***> wrote:  
 
 


Weird. And when you use your phone as access point?
And maybe try with a different ESP? Although this would be unexpected because you say that connecting to it when it is in access point mode is fine.

**Comment by MilovdZee** [comment]
No worries. We will get this to work.

**Comment by jdhysell** [comment]
The ESP is new out of the box. If I get no joy after a few morechanges, I may get another - possible DOA.
-J
    On Wednesday, April 21, 2021, 06:39:40 AM EDT, MilovdZee ***@***.***> wrote:  
 
 


No worries. We will get this to work.

**Comment by jdhysell** [comment]
Removing the Password string worked.
NTP gets updated after WiFi connect now.
thanks very much for your help.
(Now time to wire the LED array...)

Connecting to WIFI 'LIVING_ROOM'...Connected to WIFI...IP address: 10.1.254.246
Running...NTP Updated: Thu Apr 22 20:07:56 2021

    On Wednesday, April 21, 2021, 02:55:45 AM EDT, MilovdZee ***@***.***> wrote:  
 
 


You could also try your open networks by changing one line of code:
replace:
WiFi.begin(String(ssid), String(wifiPassword));
with
WiFi.begin(String(ssid));

**Comment by MilovdZee** [comment]
Probable WPA3 issue. But workaround works
